### PR TITLE
Fix documentation deployment issues

### PR DESCRIPTION
**Pull request by zbeekman**
I think this should fix the documentation deployment issues...

### CODE REVIEW

**Comment by zbeekman** [comment]
Oops, not quite fixed yet... master should build, but tagged documentation will still be borked due to https://github.com/jacobwilliams/json-fortran/commit/8afbc4a3657c9f8698ce56015029df9a82682194 interacting with https://github.com/jacobwilliams/json-fortran/blob/73d046f804bd343d4f18fc85e185d21938a76864/deploy.sh#L27

**Comment by zbeekman** [comment]
OK, I think this should be good to go...

**Comment by jacobwilliams** [comment]
Thanks! I trust you...I'm just going to merge it without checking it.

**Comment by zbeekman** [comment]
Hi Jacob,
please check your degenerateconic.com email address ASAP.

CC: @jacobwilliams

**Pull request merged**
