### PR TITLE
coverage increases

### PR DESCRIPTION
**Pull request by jacobwilliams**

### CODE REVIEW

**Comment by zbeekman** [comment]
need any help here?

**Comment by zbeekman** [comment]
Just wondering what the status of this PR/branch is

**Comment by jacobwilliams** [comment]
I haven't had time to follow up. I was trying to increase coverage by triggering more of the error conditions. But, I think I neglected to clean up after one of the errors, or something like that. Feel free to try and fix it. When I ever get around to #36, the error handling is going to be different anyway.

**Comment by jacobwilliams** [comment]
Fixed.

**Pull request merged**
