### PR TITLE
Fix #99 broken travis build

### LINKED ISSUE #99: possible travis-ci breakage
I’m not sure why but my fork of the master brach of json-fortran is erroring. It appears something about the travis-ci environment may have changed. The first error is caused by trying to install nodejs. The second error is due to gfortran-4.9 not being able to be installed anymore…. This may just be a transient travis-ci issue, but it’s worth keeping an eye on

### PR DESCRIPTION
**Pull request by zbeekman**
Fixes the mysterious travis-ci build error

### CODE REVIEW

**Comment by jacobwilliams** [comment]
Is Coveralls broke? It's still yellow.

**Comment by zbeekman** [comment]
maybe try resubmitting the travis job? I can’t seem to figure out what’s going on with coveralls. On coveralls it says coverage is 100% which is incorrect.

**Comment by zbeekman** [comment]
Coveralls is working for my fork which is encouraging. https://coveralls.io/r/zbeekman/json-fortran

**Comment by jacobwilliams** [comment]
I resubmitted and now all is well.

**Comment by zbeekman** [comment]
Lol, why coveralls? This is a 2 yr old PR

**Comment by jacobwilliams** [comment]
Better late than never, I guess!

**Pull request merged**
