### PR TITLE
Ford build updates

### PR DESCRIPTION
**Pull request by zbeekman**
- Fix .travis.yml build and testing script
  - It was trying to interpret the json-fortran.md file as a fortran source file due to extraction of sources from README.md
  - Sources extracted from README.md must have a name matching the glob `example*`
- Update CMake build to build FORD documentation, and do so as few times as possible due to speed concerns
- Clean remaining references to ROBODoc form build.sh
- Remove some old bug work arounds from build.sh and CMakeLists.txt

### CODE REVIEW

**Comment by zbeekman** [comment]
BTW, @jacobwilliams, please let me know if you want me to do a better job of separating FORD related stuff from other fixes and improvements. I can rebase this PR and pull commits unrelated to FORD out into a separate PR… with a separate feature branch.

**Comment by jacobwilliams** [comment]
Yes, if we can keep just the FORD stuff in this PR then that would be great. If it's too much trouble at this point though, then don't worry about.

**Comment by zbeekman** [comment]
OK, I’ll branch out some of the more incidental stuff to their own branches… we’ll just need to be careful when we start pulling changes into master that we have merged changes from accepted PRs into outstanding PRs, or rebase outstanding PRs against master. (The latter approach is my preference… but can be a little tricky to resolve conflicts.)

**Comment by zbeekman** [comment]
I’ve cherry picked the unrelated commits into their own branches and submitted PRs against master for those… Once you merge them into master, you should either rebase the `ford` branch against master, or pull changes from master into the ford branch.

```
#after merging PRs against master
git co master
git pull origin master
git co ford
git rebase master # or git pull master
```

I think :pray: that my PRs against master won’t cause any merge conflicts when you do that… Let me know if they do and I can help you sort them out and any other git issues you run into.

**Comment by jacobwilliams** [comment]
Cross your fingers..

**Pull request merged**
