### PR TITLE
badges and waffle.io

### PR DESCRIPTION
**Pull request by zbeekman**
Do you have any interest in adding some badges (releases/versions, issues, and CI status) to the home page?

Also, waffle.io is a pretty neat and configurable tool to help automate the issue tracking and collaborative work on the issue backlog. It’s pretty easy to learn and straightforwards too.

### CODE REVIEW

**Comment by zbeekman** [comment]
I can change the format etc. if you like.

**Comment by jacobwilliams** [comment]
Will take a look!  Interesting...I don't remember ever signing up for this... maybe I did and just forgot, or it added one automatically?

**Comment by zbeekman** [comment]
Actually, it probably just creates them for every public repo…

Also, FYI, you can drag the columns to reorder them… I like to put needs review to the left of recently closed, so that issues flow from left to right…

**Comment by zbeekman** [comment]
Also, moving issues to ready on waffle.io let’s collaborators and community members know that they can start working on them… moving them to in progress and assigning them lets people know that that issue is being claimed and worked on by someone.

Furthermore, if you create a feature or bug fix branch with the issue in the name, waffle.io will automatically move the issue to “In Progress” 

I think that the feature branch development approach is nice so that you don’t end up with broken states in your revision history in master…

—just my $0.02

If you added me as a collaborator I could help manage all that, and would still only make contributions through pull request, although perhaps it would make sense to do so from a feature branch in your repo, rather than my fork…

**Comment by jacobwilliams** [comment]
Yes, I need to use branches, rather than just committing everything to the master (which is what I've done up to this point).  It is a good policy.  Let me think about collaborators.  I'd kind of like to remain the benevolent dictator for pushes to the master branch for now.  Does GitHub let me specify fine-grained permissions for other activities?  I don't think it does...will look into it.

**Comment by zbeekman** [comment]
I don’t think it does either… that would be ideal. I completely understand, just spit balling.

**Comment by szaghi** [comment]
Dear all,

I just see the Izaak settings of waffles columns... very nice! You add a sort of "scientific rational" to them! Can I copy your idea? :-)

See you soon.

**Comment by szaghi** [comment]
Moreover, I like also the meaningful placement of badges into the main README... I surely will copy you!

Great work!

**Comment by zbeekman** [comment]
Just FYI @jacobwilliams and @jacobwilliams you can use http://shields.io to create alternate/custom shields for some services. For example in f5fc1b95f5ee084ca7f46c46c089abd0c5b6d024 I swapped the travis-ci badge for a `plastic` style badge so that it matches the waffle.io badges, which, currently, cannot be customized. It’s not always clear what services http://shields.io supports, or how to use the website, but I think they’re working on improving the documentation.

**Comment by szaghi** [comment]
@zbeekman and @jacobwilliams I have just (ab)used of the http://shields.io server. In particular, I like to use their user-customized badge to clearly indicate

+ the license;
+ the compilers support;

It is very simple, see [this](https://github.com/szaghi/FLAP).

See you soon.

**Comment by zbeekman** [comment]
@szaghi haha, abuse indeed! :stuck_out_tongue_closed_eyes:

As for the applicability to this project, json-fortran, I have the following comments:
 1. I like the idea of a license badge, but it seems that the json-fortran license is just “BSD-style”, so I’m not sure what the text of such a badge should read. Maybe @jacobwilliams has thoughts on this matter.
 2. The compiler compatibility section is a bit too cluttered for my liking, on the FLAP page. Also, it would be nice to have at least some of the compiler badges dynamically update through travis-ci, but this is probably only doable for gfortran due to licensing issues.

**Comment by szaghi** [comment]
Hi Izaak,

you are right, I have abused of badges (and too many other things)!

For the auto-update of compiler compatibility by means of travis-ci, I think there is no way. Travis provides a build pass check... but I don't know if there is a way to use other compiler rather than GNU gfortran.

See you soon.

**Comment by zbeekman** [comment]
yeah, I think you can only use gfortran… but you might be able to change the text of the travis-ci build badge to repurpose it as a gfortran badge

**Pull request merged**
