### PR TITLE
Feat utf 8 support issue 35

### PR DESCRIPTION
**Pull request by zbeekman**
I still need to add a test case for Unicode support but the build scripts have been updated and the library has been updated. I’m going to post the diff of the library to a gist since it’s to big to be directly displayed in the github commit for 0d86120.

diff: http://git.io/pgRf

### CODE REVIEW

**Comment by zbeekman** [comment]
In addition the documentation isn’t 100% updated, any help with that would be much appreciated. I still have my ROBODoc training wheels on.

**Comment by jacobwilliams** [comment]
Merge it, or are you still adding stuff?  Just let me know.  I can help with documentation, etc.  There will be major conflicts with the "speed" branch...but I still have some work to do on that, and will get to it at some point.

**Comment by zbeekman** [comment]
I am planning to add a test before we merge.

I think the speed branch will be challenging, beyond just merge conflicts. UTF8 encoding is variable length, which will break unformatted stream reads. (Also, ISO 10646 characters are stored in 4 bytes.) BUT, we may be able to `inquire` if a file is UTF8 encoded to determine how to read it, and only ask for UTF8 encoding if it's needed, although this will be more challenging.

**Comment by jacobwilliams** [comment]
OK.  If you don't mind, make it test_11, since I've already got a test_10 in the unit-test branch that I'm working on.

**Comment by zbeekman** [comment]
Yup, I noticed that. Should I give it a more descriptive name? `jf_test_unicode.f90` or stick with numeric? (The former will get picked up and run with the current lobbing setup.)

**Comment by zbeekman** [comment]
Just to clarify both naming schemes require no modification of the build infrastructure

**Comment by zbeekman** [comment]
I just need to make sure this passes the travis tests, then we should be good to go. I’ll come back and leave a thumbs up here as soon as I deem this ready.

**Comment by zbeekman** [comment]
hmmm I think I introduced an error with the build script…

**Comment by zbeekman** [comment]
:+1: ready to merge…

I don’t understand why when I fixed the build script issue (via rebasing) the coverage went down… I actually added a call to an uncovered procedure in test_11 when I did that, so, if anything, coverage should have gone up…. I don’t really know the best way to figure out why that’s happening.

**Comment by zbeekman** [comment]
OK… don’t merge yet… something happened to test 11….

**Comment by zbeekman** [comment]
I have no idea why the coverage went down and can’t figure it out… I think this is OK and ready to merge now, either way. I’m going to chalk up the coverage issue to a gcov or coveralls bug… I could be wrong but can’t figure out why the coverage jumped down.

**Comment by zbeekman** [comment]
FYI, this is ready to go, IMO :+1:

**Comment by jacobwilliams** [comment]
About to merge.  Cross your fingers...

**Comment by jacobwilliams** [comment]
I'm going to clean up the Robodoc headers a bit.

**Comment by zbeekman** [comment]
Yeah, my apologies but many of the wrappers don't have ROBODoc headers and neither do some of the new helper procedures like the concatenation operator.

**Comment by zbeekman** [comment]
if you need or want help resolving conflicts pulling in these changes to your speed or unit test branches let me know, I’ll try to help resolve them

**Comment by jacobwilliams** [comment]
No problem.  Will commit an update soon.

Yes...likely I will need help. Although this may be my opportunity to finally become a git master... will let you know.

**Pull request merged**
